name = "cloudnexus-on-cf"
compatibility_date = "2024-01-01"

# D1数据库绑定配置
[[d1_databases]]
binding = "DB"
database_name = "2025-03-05-docupload-d1"
database_id = "8f1dedcc-bb7c-449c-89e3-d0dc28afbba9"

# 静态资源配置
[site]
bucket = "./dist"

# 开发环境配置
[dev]
port = 8788

# R2存储桶绑定配置
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "2025-03-05-docupload"

# 环境变量配置
[vars]
JWT_SECRET = "your-secure-jwt-secret-key"

[env.production.vars]
JWT_SECRET = "your-production-jwt-secret-key"