name = "cloudnexus-on-cf"
compatibility_date = "2024-01-01"

# D1数据库绑定配置
[[d1_databases]]
name = "DB"
database_name = "cloudnexus-db"
database_id = "your-database-id"

# 静态资源配置
[site]
bucket = "./dist"

# 开发环境配置
[dev]
port = 8788