name = "cloudnexus-on-cf"
compatibility_date = "2024-01-01"

# D1数据库绑定配置
[[d1_databases]]
binding = "DB"
database_name = "cloudnexus-db"
database_id = "8f1dedcc-bb7c-449c-89e3-d0dc28afbba9"

# 静态资源配置
[site]
bucket = "./dist"

# 开发环境配置
[dev]
port = 8788